forex/urls.py
from django.conf.urls import url
from django.contrib import admin

from trades.rest_api import TradeListCreateApiView, GetRateApiView
from trades.views import ForExTradesView, ListTradesAngularTemplateView, NewTradeAngularTemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # RESTful API
    url(r'^api/trades/$',
        TradeListCreateApiView.as_view(),
        name='TradeListCreateApiView'),
    url(r'^api/rates/$',
        GetRateApiView.as_view(),
        name='GetRateApiView'),

    url(r'^angular_templates/list_trades.html$',
        ListTradesAngularTemplateView.as_view(),
        name='ListTradesAngularTemplateView'),
    url(r'^angular_templates/new_trade.html$',
        NewTradeAngularTemplateView.as_view(),
        name='NewTradeAngularTemplateView'),

    url(r'^',
        ForExTradesView.as_view(),
        name='ForExTradesView'),
]

trades/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.crypto import get_random_string


class Currency(models.Model):
    code = models.CharField(max_length=3, unique=True,
                            verbose_name=_('Code'))

    class Meta:
        verbose_name = _('Currency')
        verbose_name_plural = _('Currencies')
        ordering = ('code',)

    def __str__(self):
        return self.code


class Trade(models.Model):
    id = models.CharField(max_length=9, primary_key=True)
    sell_currency = models.ForeignKey(Currency,
                                      related_name='selling_trades',
                                      verbose_name=_('Sell CCY'))
    sell_amount = models.DecimalField(max_digits=9, decimal_places=2,
                                      verbose_name=_('Sell amount'))
    buy_currency = models.ForeignKey(Currency,
                                     related_name='buying_trades',
                                     verbose_name=_('Buy CCY'))
    buy_amount = models.DecimalField(max_digits=9, decimal_places=2,
                                     verbose_name=_('Buy amount'))
    rate = models.DecimalField(max_digits=7, decimal_places=4,
                               verbose_name=_('Rate'))
    date_booked = models.DateTimeField(verbose_name=_('Date booked'),
                                       auto_now_add=True)

    class Meta:
        verbose_name = _('Trade')
        ordering = ('-date_booked',)

    def __str__(self):
        return self.id

    def save(self, *args, **kwargs):
        # TODO The specification doesn't make it clear if ids should be randomized. This should be clarified
        while not self.id:
            random_part = get_random_string(7, allowed_chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789')
            random_id = 'TR%s' % random_part
            if not type(self).objects.filter(pk=random_id).count():
                self.id = random_id

        super().save(*args, **kwargs)

trades/views.py
import json

from django.views.generic import TemplateView

from trades.models import Currency


class ForExTradesView(TemplateView):
    template_name = 'trades/main.html'

    def get_context_data(self, **kwargs):
        context = super(ForExTradesView, self).get_context_data(**kwargs)
        qs_currencies = Currency.objects.all()
        currencies = [{'id': currency.id, 'code': currency.code}
                      for currency in qs_currencies]
        context['currencies_json'] = json.dumps(currencies)
        return context


class ListTradesAngularTemplateView(TemplateView):
    template_name = 'trades/list_trades.html'


class NewTradeAngularTemplateView(TemplateView):
    template_name = 'trades/new_trade.html'

forex/templates/trades/list_trades.html
{% load i18n %}

<div class="row">
  <div class="col-md-offset-1 col-md-10 title-container">
    <h1>{% trans 'Booked Trades' %}</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <a class="btn btn-primary pull-right" href="/new_trade">{% trans 'New Trade' %}</a>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <table class="table table-striped" id="table_trades">
    <thead>
      <tr>
        <th>{% trans 'Sell CCY' %}</th>
        <th>{% trans 'Sell Amount' %}</th>
        <th>{% trans 'Buy CCY' %}</th>
        <th>{% trans 'Buy Amount' %}</th>
        <th>{% trans 'Rate' %}</th>
        <th>{% trans 'Date Booked' %}</th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="trade in trades">
        <td ng-bind="trade.sell_currency"></td>
        <td ng-bind="trade.sell_amount|currency:''"></td>
        <td ng-bind="trade.buy_currency"></td>
        <td ng-bind="trade.buy_amount|currency:''"></td>
        <td ng-bind="trade.rate"></td>
        <td ng-bind="trade.date_booked|date:'dd/MM/yyyy HH:mm'"></td>
      </tr>
    </tbody>
  </table>
  </div>
</div>

forex/templates/trades/main.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html ng-app="ForexApp">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% trans "Foreign Exchanges Trades" %}</title>

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <style media="screen">
    .title-container {
      border-bottom: 2px solid black;
      margin-bottom: 2%;
    }
    #table_trades {
      margin-top: 2%;
    }
    #table_trades td,
    #table_trades th {
      text-align: center;
    }
    input[readonly] {
      background-color: lightgray;
    }
  </style>
</head>
<body>
<div class="container-fluid" ng-view></div>

<script src="{% static 'js/angular.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/angular-route.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/angular-resource.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/app.js' %}" charset="utf-8"></script>
<script src="{% static 'js/controllers.js' %}" charset="utf-8"></script>
<script type="text/javascript">
var templateListTrades = '{% url "ListTradesAngularTemplateView" %}';
var templateNewTrade = '{% url "NewTradeAngularTemplateView" %}';
var urlTradesEndpoint = '{% url "TradeListCreateApiView" %}';
var urlGetRateEndpoint = '{% url "GetRateApiView" %}';
var currenciesJson = {{ currencies_json|safe }};
</script>
</body>
</html>

forex/templates/trades/new_trade.html
{% load i18n %}

<form method="post" name="newTradeForm">
<div class="row">
  <div class="col-md-offset-1 col-md-10 title-container">
    <h1>{% trans 'New Trade' %}</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-2 col-md-3">
    <div class="form-group">
      <label for="id_sell_currency">{% trans 'Sell Currency' %}</label>
      <select class="form-control" id="id_sell_currency"
              ng-model="sellCurrency" ng-change="retrieveRate()">
        <option value="" selected>&mdash;</option>
        <option ng-repeat="currency in currencies"
                ng-bind="currency.code"
                value="{% verbatim %}{{ currency.id }}{% endverbatim %}">
        </option>
      </select>
    </div>
    <div class="form-group">
      <label for="id_sell_amount">{% trans 'Sell Amount' %}</label>
      <input type="number" class="form-control" id="id_sell_amount"
             name="sell_amount" ng-model="sellAmount" step="0.01">
      <div class ="row-fluid alert alert-danger" ng-if="!newTradeForm.sell_amount.$valid">
        {% trans "<strong>Sell amount not valid</strong>. You must specify a maximum of 2 decimal places." %}
      </div>
    </div>
  </div>

  <div class="col-md-2">
    <div class="row-fluid">
      <div class="col-md-12 text-center">
        <strong>{% trans 'Rate' %}</strong>
        <input type="hidden" id="id_rate" ng-model="rate">
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-md-4 text-center">
        <span class="glyphicon glyphicon-play"></span>
      </div>
      <div class="col-md-4 text-center" ng-bind="rate || '&mdash;'"></div>
      <div class="col-md-4 text-center">
        <span class="glyphicon glyphicon-play"></span>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="form-group">
      <label for="id_buy_currency">{% trans 'Buy Currency' %}</label>
      <select class="form-control" id="id_buy_currency"
              ng-model="buyCurrency" ng-change="retrieveRate()">
        <option value="" selected>&mdash;</option>
        <option ng-repeat="currency in currencies"
                ng-bind="currency.code"
                value="{% verbatim %}{{ currency.id }}{% endverbatim %}">
        </option>
      </select>
    </div>
    <div class="form-group">
      <label for="id_buy_amount">{% trans 'Buy Amount' %}</label>
      <input type="text" class="form-control" id="id_buy_amount"
             ng-model="buyAmount" readonly>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <button class="btn btn-primary" ng-click="createTrade()"
            ng-disabled="!buyAmount">
      {% trans 'Create' %}
    </button>
    <a class="btn btn-default pull-right" href="/">
      {% trans 'Cancel' %}
    </a>
  </div>
</div>
</form>